-- AlterTable
ALTER TABLE "Inflow" ALTER COLUMN "costAmount" SET DATA TYPE DECIMAL(18,2),
ALTER COLUMN "saleAmount" SET DATA TYPE DECIMAL(18,2);

-- AlterTable
ALTER TABLE "Outflow" ALTER COLUMN "saleAmount" SET DATA TYPE DECIMAL(18,2),
ALTER COLUMN "costAmount" SET DATA TYPE DECIMAL(18,2);

-- AlterTable
ALTER TABLE "Product" ALTER COLUMN "costPrice" SET DATA TYPE DECIMAL(18,6),
ALTER COLUMN "salePrice" SET DATA TYPE DECIMAL(18,2);

-- AlterTable
ALTER TABLE "Sale" ALTER COLUMN "saleAmount" SET DATA TYPE DECIMAL(18,2),
ALTER COLUMN "costAmount" SET DATA TYPE DECIMAL(18,2);

-- AlterTable
ALTER TABLE "Withdraw" ALTER COLUMN "amount" SET DATA TYPE DECIMAL(18,2);
